name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
      - "ci"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Lint
        run: |
          ls ${{ github.workspace }}
          pip install pylint
          pylint life_expectancy.cleaning
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        run: |
          pip install pytest pytest-cov
          pytest life_expectancy --cov 
