name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
      - "ci"
      - "refactoring"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
      - name: Lint
        run: |
          pip install pylint
          pylint life_expectancy.cleaning
      - name: Test
        run: |
          pip install pytest pytest-cov
          pytest life_expectancy --cov 
